config/routes.rb
Jists::Application.routes.draw do

  match 'new' => 'jists#new', :as => :new_jist, :via => :get
  match 'jists' => 'jists#index', :as => :jists, :via => :get
  match ':id/edit' => 'jists#edit', :as => :edit_jist, :via => :get
  match ':id/(:sha)' => 'jists#show', :as => :jist, :via => :get
  match 'jists' => 'jists#create', :via => :post
  match ':id' => 'jists#update', :via => :put
  match ':id' => 'jists#destroy', :via => :delete
  root :to => 'jists#new'

end

app/models/jist.rb
class Jist < ActiveRecord::Base

  # The path to where the repos are saved
  REPO_PATH = Jists::Application.config.repo_path

  after_save :update_repo

  # The first file's contents "saved" for when repo is set up
  def paste=(paste)
    @paste = paste
  end

  def files=(jistfiles)
    @files = jistfiles
  end

  # Returns first file's contents for new/edit textarea
  def paste
    head.tree.blobs.first.data.to_s if repo.present?
  end

  # Public: Each file's data including filename and contents
  #
  # commit_ref - A String SHA of the files at the time of the commit
  #              (default - "HEAD")
  #
  # Returns an Array
  def files(commit_ref = nil)
    files = []
    sha = commit_ref.present? ? commit_ref : head.id

    repo.commit(sha).tree.contents.map do |blob|
      files << { name: blob.name, data: blob.data }
    end

    return files
  end

  # Public: The latest commit in the repo
  #
  # Returns a Grit::Commit
  def head
    repo.head.commit
  end

  # Public: List of commits
  #
  # Returns an Array of Grit::Commits
  def commits
    repo.commits
  end

  # Find or create a Grit::Repo unless self is not persisted
  #
  # Returns a Grit::Repo
  def repo
    @repo ||= Grit::Repo.init_bare_or_open("#{REPO_PATH}#{id}.git") unless new_record?
  end

  # ===========================================================================
  # PRIVATE
  # ===========================================================================

  private

  # Update the Grit::Repo with the paste data
  #
  # TODO: Accept a custom commit message
  # TODO: Accept a filename and extension
  # TODO: Accept multiple files
  def update_repo
    r = repo
    i = r.index
    i.read_tree 'master'

    @files.each do |file, data|
      if data['filename'].present?
        i.add data['filename'], @paste.to_s
      else
        i.add "#{ file }.txt", @paste.to_s
      end
    end

    if r.commit_count.zero?
      i.commit 'Initial Commit'
    else
      i.commit '', [repo.commits.first]
    end
    touch :updated_at
  end

  # Replace non-word characters with underscores
  #
  # Returns a String
  def sanitize_filename(filename)
    # http://devblog.muziboo.com/2008/06/17/attachment-fu-sanitize-filename-regex-and-unicode-gotcha/
    # filename.strip!
    # TODO: Check for and sanitize extension
    # Replace all non alphanumeric, underscore or periods with underscore
    # filename.gsub!(/[^0-9A-Za-z.\-]/, '_')
    # TODO: Replace multiple underscores with a single underscore
    # filename.gsub!(/_{2,}/, '_')
    # TODO: Remove any trailing underscores before file extension
    # filename.gsub!(/(_.)/, '.')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jists_controller.rb
class JistsController < ApplicationController

  def index
    @jists = Jist.all
  end

  def show
    @jist = Jist.find(params[:id])
    @commit = params[:sha] ? params[:sha] : @jist.head.id
  end

  def new
    @jist = Jist.new
  end

  def create
    @jist = Jist.new(params[:jist])
    
    respond_to do |format|
      if @jist.save
        format.html { redirect_to(@jist, :notice => 'Jist was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @jist = Jist.find(params[:id])
  end

  def update
    @jist = Jist.find(params[:id])

    respond_to do |format|
      if @jist.update_attributes(params[:jist])
        format.html { redirect_to(@jist, :notice => 'Jist was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @jist = Jist.find(params[:id])
    @jist.destroy

    respond_to do |format|
      format.html { redirect_to(root_path, :notice => 'Jist was successfully deleted.') }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jists_helper.rb
module JistsHelper

  def file_language(file)
    case File.extname(file)
    when '.coffee'
      'coffeescript'
    when '.css'
      'css'
    when '.html'
      'html'
    when '.js'
      'javascript'
    when '.php'
      'php'
    when '.py'
      'python'
    when '.rb'
      'ruby'
    when '.sh'
      'shell'
    end
  end

end

app/views/jists/_form.html.erb
<%= form_for jist do |f| %>

  <header class="cf">
    <h1 class="title">
      <%= content_tag(:span, "##{ jist.id }", class: 'id') unless jist.new_record? %>
      <%= f.text_field :description, placeholder: 'Jist description' %>
    </h1>
  </header>

  <section class="files">
    <% if @jist.persisted? %>
      <% @jist.files(@commit).each do |file| %>
        <article class="file">
          <h1 class="filename"><%= file[:name] %></h1>

          <%= f.text_area :paste, class: 'contents', autofocus: true %>
        </article>
      <% end %>
    <% else %>
      <article class="file">
        <h1 class="filename"><%= text_field_tag 'jist[files][jistfile_1][filename]', "" , placeholder: 'Name this file...' %></h1>
        <%= f.text_area :paste, class: 'contents', autofocus: true %>
      </article>
    <% end %>
  </section>

  <div class="field">
    <%= f.submit %> <% if jist.persisted? %>or <%= link_to 'cancel', jist %><% end %>
  </div>

<% end %>

app/views/jists/edit.html.erb
<section class="jist edit">
  <%= render :partial => "form", :locals => { :jist => @jist } %>
</section>

app/views/jists/index.html.erb
<article class="jists index">
  <h1>All Jists</h1>

  <ul class="jists-list">
    <% @jists.each do |jist| %>
      <li><%= link_to "##{ jist.id }", jist %> <span class="description">– <%= jist.description %></span></li>
    <% end %>
  </ul>
</article>

app/views/jists/new.html.erb
<section class="jist new">
  <%= render :partial => "form", :locals => { :jist => @jist } %>
</section>

<% content_for :secondary do -%>
  <aside class="recently-updated">
    <h3>Recently Updated</h3>
    <ul>
      <% Jist.order('updated_at DESC').limit(20).each do |jist| %>
        <li><%= link_to "##{jist.id}", jist %> <span class="description"><%= jist.description %></span></li>
      <% end %>
    </ul>
  </aside>
<% end -%>

app/views/jists/show.html.erb
<article class="jist show">

  <header class="cf">
    <h1 class="title"><span class="id"><%= "##{ @jist.id }:" %></span> <span class="description"><%= @jist.description %></span></h1>
    <ul class="controls">
      <li><%= link_to "Edit", edit_jist_path(@jist), class: 'edit' %></li>
    </ul>
  </header>

  <section class="files">
    <% @jist.files(@commit).each do |file| %>
      <article class="file">
        <h1 class="filename"><%= file[:name] %></h1>

        <pre class="contents" data-language="<%= file_language file[:name] %>">
          <code><%= file[:data] %></code>
        </pre>
      </article>
    <% end %>
  </section>

  <section class="actions">
    <%= link_to "Delete this Jist", jist_path(@jist), method: :delete, confirm: 'Are you sure? This Jist will be permanently deleted.', class: 'destroy' %>
  </section>

</article>

<% content_for :secondary do -%>
  <aside class="history">
    <h3>History</h3>
    <ol class="commits">
      <% @jist.commits.each do |commit| %>
        <li><%= link_to commit.id, jist_path(@jist, commit.id) %> <b class="author"><%= commit.author %></b> <time class="authored_date"><%= commit.authored_date %></time></li>
      <% end %>
    </ol>
  </aside>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />

	<!-- Make a DNS handshake with a foreign domain, so the connection goes faster when the user eventually needs to access it. This works well for loading in assets (like images) from another domain, or a JavaScript library from a CDN. -->
	<link rel="dns-prefetch" href="//ajax.googleapis.com" />
	<link rel="dns-prefetch" href="//s3.amazonaws.com" />
	<!-- Make sure the latest version of IE is used -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<!-- Link to Sitemap -->
	<link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml" />

	<!-- Main Page Title -->
	<title>Jists</title>
	<!-- Content Information -->
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta name="author" content="" />

	<!-- Canonical URL -->
	<link rel="canonical" href="" />

	<!-- Mobile viewport optimized: j.mp/bplateviewport -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

	<!-- Suppress IE6 Image Toolbar -->
	<meta http-equiv="imagetoolbar" content="false" />

	<!-- CSS: implied media="all" -->
  <%= stylesheet_link_tag "application", :media => "all" %>

	<!-- JQuery from Google -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

	<!-- Load JS (Should be at bottom) -->
  <%= javascript_include_tag "application" %>

	<!-- HTML5 Shim -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

  <%= csrf_meta_tags %>

</head>
<body>

  <header id="banner">
    <div class="wrapper">
      <h1 class="title"><%= link_to "Jist", root_url %></h1>
    </div>
  </header>

  <div class="wrapper">

    <div id="secondary">
      <%= yield :secondary %>
    </div>

    <div id="main" role="main">
      <%= yield %>
    </div>

  </div>

</body>
</html>